### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by herbaceousBackson** [redecheck/redecheck-tool#1]
Hi, this is a really interesting tool and I'm interested in using it but I can't run it...

I downloaded and installed it in the development environment recommended in the readme:
     OS is Ubuntu Linux 15.04 "Vivid Vervet"
     Java Standard Edition 1.8
     Mozilla Firefox 44

The project builds successfully using maven from the command line.

But when I try to run it, I get this:
![screenshot from 2017-05-04 09 17 13](https://cloud.githubusercontent.com/assets/26891581/25690008/90806b92-30aa-11e7-91c8-703346985fce.png)
![screenshot from 2017-05-04 09 17 21](https://cloud.githubusercontent.com/assets/26891581/25690027/b6367f16-30aa-11e7-834a-2c17d92b2d1f.png)

I have no idea what I might be doing wrong, so if you could help me out I'd be really grateful!

Thanks!

**Comment by twalsh92** [comment]
Hello,

First of all, thank you for your interest in ReDeCheck and we’re sorry to hear you’re having trouble running it.

We’ve looked into the issue you appear to be having and believe the issue to be with the geckodriver file located in the /resources directory and the solution should be fairly simple. As you’re running Linux as your OS, you’ll need to replace the version of geckodriver with a linux version available here:

https://github.com/mozilla/geckodriver/releases.

We tested it with Firefox 44 and version 0.14.0 of geckodriver on a Linux virtual machine and everything seemed to work OK. Hopefully it’ll resolve your issue. We’ll be modifying the readme instructions so hopefully no-one else has this issue in the future.

As ReDeCheck is still in the prototype stage, we’d love to hear feedback from you. If you’re still having problems running the tool, would like to get in touch, or would like to know more about the tool, please feel free to email redechecktool@gmail.com and I’ll be happy to help.

Once again, thank you for your interest in ReDeCheck.

Kind Regards,

Thomas Walsh

**Comment by herbaceousBackson** [comment]
Hi Mr. Walsh, thanks for your response.

Unfortunately, I'm still getting the same errors. 

I downloaded version 0.14.0 of geckodriver, extracted it and put it in the /resources directory. Is that all there is to do to use the new driver, or am I missing some steps? Because the error I'm getting looks the same to me. I'll post the screenshots anyway in case you can find some clue as to what I'm doing wrong:

![screenshot from 2017-05-04 18 58 25](https://cloud.githubusercontent.com/assets/26891581/25706134/2ac1b2d6-30fd-11e7-8cdc-04f504c02004.png)
![screenshot from 2017-05-04 18 58 32](https://cloud.githubusercontent.com/assets/26891581/25706150/35bafa6c-30fd-11e7-8ddd-6d6d02e57fb9.png)

**Comment by twalsh92** [comment]
Hi,

I've managed to reproduce the error from your screenshots and it seems to be a communication error between Selenium and Firefox. It's quite widely documented online that the compatibility between different versions of the two can be hard to predict.

I installed Firefox 46 on my machine which runs fine. I know it's not the most elegant solution, but might be the best way to resolve the issue.

Thanks,

Thomas Walsh

**Comment by herbaceousBackson** [comment]
Ok so switching to Firefox 46 has definitely fixed something. 

It now opens the site in a browser window and then spends some time in another window resizing it. 

However it then terminates with this?:

![screenshot from 2017-05-05 09 18 08](https://cloud.githubusercontent.com/assets/26891581/25733159/073daa6e-3174-11e7-871a-90b59a62ba69.png)

**Comment by twalsh92** [comment]
OK, that error is unusual as it seems to be to do with the tool not extracting the layout of the webpage from the browser.

Would you be able to try it on one of the other webpages from the README.md and see if the issue persists? Here's a list of the URLs:

http://duolingo.com

http://midwaymeetup.com

http://pdfescape.com

http://willmyphonework.net

http://hotelwifitest.com

Sorry again for all the problems. Hopefully we'll have everything set up correctly soon!

**Comment by herbaceousBackson** [comment]
Ok, I've tried it now on those five URLs, I'm still getting errors, but they seem to be a little different each time, so I'll post the screenshots below:

duolingo.com:
![screenshot from 2017-05-05 20 10 05](https://cloud.githubusercontent.com/assets/26891581/25751041/4e999f14-31d1-11e7-90e4-d54a62cdd211.png)

midwaymeetup.com:
![screenshot from 2017-05-05 20 13 02](https://cloud.githubusercontent.com/assets/26891581/25751095/7b8b8a78-31d1-11e7-8de5-86c930ab684a.png)

pdfescape.com:
![screenshot from 2017-05-05 20 14 37](https://cloud.githubusercontent.com/assets/26891581/25751148/9fc4e65a-31d1-11e7-86e3-0ad3fcafd182.png)

willmyphonework.net:
![screenshot from 2017-05-05 20 22 04](https://cloud.githubusercontent.com/assets/26891581/25751205/d0b25fae-31d1-11e7-9744-445d9cba2a99.png)

hotelwifitest.com:
![screenshot from 2017-05-05 20 24 57](https://cloud.githubusercontent.com/assets/26891581/25751266/ff8978ee-31d1-11e7-8d34-891e3475321f.png)
![screenshot from 2017-05-05 20 25 01](https://cloud.githubusercontent.com/assets/26891581/25751308/2edc586e-31d2-11e7-99cb-3f23d5c36e01.png)

**Comment by twalsh92** [comment]
Hi,

We think we've managed to diagnose the issue. The error message "Invalid requested size, cannot maximise" was being caused by the tool trying to resize the browser to a width larger than the display. We've pushed a fix which should remedy the issue automatically, so if you pull those changes and repackage with Maven it should now run correctly. You can also set the maximum width to sample using the command line argument --end 1200, for example, to ensure the tool doesn't try and resize the browser to a size bigger than your screen.

If you'd just like to try the tool, we're in the process of uploading a virtual machine where the tool is set up. We'll post the link once it's all uploaded online. Hopefully, you'll be able to run it on your own machine though.

Best,

Thomas Walsh

**Comment by herbaceousBackson** [comment]
Hmm, I'm still getting the same errors at the moment :/

I suppose I'll wait for the virtual machine then :)

**Comment by twalsh92** [comment]
Ok, it turns out the browser height the tool was using was also causing issues on some displays, so we've pushed a patch through which should remedy it. If you pull the latest version of the tool and repackage it through maven (mvn package), it should now work.

To ensure the tool isn't trying to resize the browser too wide, could you run it with the --end argument set to a value smaller than the width of your display, like in the example below? 

`java -jar redecheck-jar-with-dependencies.jar --end 1100 --url http://hotelwifitest.com`

If the error persists, could you provide another screenshot showing the error message to help us diagnose and fix the issue?

We've also uploaded a virtual machine where the tool is runnable for you to try. It's available from the following link on Google Drive with no need to sign in. Simply follow the instructions in the accompanying Google Doc and you should be good to go.

https://drive.google.com/open?id=0B3Um_80VuL0ycTlibUE1OE5lSmc

Thanks,

Thomas Walsh

**Comment by herbaceousBackson** [comment]
Hi again, sorry for the massive delay...

So I pulled the latest version and repackaged it. 

It seems to be working! For most sites at least. With and without the --end argument.

I tried it on those five URLs above, and for four out of five of them it worked perfectly without any issues.

However, when I tried it on pdfescape.com I get this:
![screenshot from 2017-05-19 16 41 02](https://cloud.githubusercontent.com/assets/26891581/26245689/f0ae26ee-3cb2-11e7-8f92-7c670f787771.png)

Also, I tried using the virtual machine, but I wasn't able to extract ReDeCheck.zip, I tried extracting it in Ubuntu and also in Windows using 7-zip. Possibly the file got corrupted?

**Comment by twalsh92** [comment]
Hi,

I'm very glad to hear that the tool is working correctly for most of the sites. Unfortunately, I've again been unable to replicate the issue, but what I can ascertain from my research into the issue is that you may need to authorise pop-ups for that website in your Firefox installation, which you can do via "Preferences" -> "Content" -> "Exceptions". I'm unsure as to whether this will remedy the issue though.

As for the VM, the issue seems to have been that the files were zipped on MacOS, which can cause decompression issues on other operating systems. I've reuploaded things onto the Google Drive folder which should work this time around.

https://drive.google.com/open?id=0B3Um_80VuL0ycTlibUE1OE5lSmc 

Thanks,

Thomas Walsh
